// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCSwX5COo9QHVYNiucQ8OuHhcxO1Smw34',
    appId: '1:434937925608:android:61421ac6977a76040b5e5d',
    messagingSenderId: '434937925608',
    projectId: 'live-translator-b9501',
    storageBucket: 'live-translator-b9501.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFgi-0zx9QyvQE6NVlDQixqZT5W3AbXCg',
    appId: '1:434937925608:ios:3b1897c2acfe76620b5e5d',
    messagingSenderId: '434937925608',
    projectId: 'live-translator-b9501',
    storageBucket: 'live-translator-b9501.firebasestorage.app',
    androidClientId: '434937925608-gro7jiuu6ejmhcpirhs4lot9ek4bq18u.apps.googleusercontent.com',
    iosClientId: '434937925608-tfm0bkeeagctm4q1bl8lotgbt0ed1sup.apps.googleusercontent.com',
    iosBundleId: 'com.ghassanalhattali.livetranslator',
  );
}
